#!/bin/bash

# Transfer (adv=0.05 + recon=0.1), attr_vectors_avg_diff. Sens. attr - Pale_Skin

./celeba_pipelines.sh e2e --classify_attributes Smiling --perturb Pale_Skin --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes High_Cheekbones --perturb Pale_Skin --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Mouth_Slightly_Open --perturb Pale_Skin --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Wearing_Lipstick --perturb Pale_Skin --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Heavy_Makeup --perturb Pale_Skin --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Wavy_Hair --perturb Pale_Skin --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Arched_Eyebrows --perturb Pale_Skin --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"

# Transfer (adv=0.05 + recon=0.1), attr_vectors_avg_diff. Sens. attr - Young

./celeba_pipelines.sh e2e --classify_attributes Smiling --perturb Young --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes High_Cheekbones --perturb Young --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Mouth_Slightly_Open --perturb Young --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Wearing_Lipstick --perturb Young --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Heavy_Makeup --perturb Young --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Wavy_Hair --perturb Young --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Arched_Eyebrows --perturb Young --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"

# Transfer (adv=0.05 + recon=0.1), attr_vectors_avg_diff. Sens. attr - Blond_Hair

./celeba_pipelines.sh e2e --classify_attributes Smiling --perturb Blond_Hair --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes High_Cheekbones --perturb Blond_Hair --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Mouth_Slightly_Open --perturb Blond_Hair --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Wearing_Lipstick --perturb Blond_Hair --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Heavy_Makeup --perturb Blond_Hair --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Wavy_Hair --perturb Blond_Hair --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Arched_Eyebrows --perturb Blond_Hair --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"

# Transfer (adv=0.05 + recon=0.1), attr_vectors_avg_diff. Sens. attr - Pale_Skin,Young

./celeba_pipelines.sh e2e --classify_attributes Smiling --perturb "Pale_Skin,Young" --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes High_Cheekbones --perturb "Pale_Skin,Young" --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Mouth_Slightly_Open --perturb "Pale_Skin,Young" --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Wearing_Lipstick --perturb "Pale_Skin,Young" --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Heavy_Makeup --perturb "Pale_Skin,Young" --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Wavy_Hair --perturb "Pale_Skin,Young" --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Arched_Eyebrows --perturb "Pale_Skin,Young" --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"

# Transfer (adv=0.05 + recon=0.1), attr_vectors_avg_diff. Sens. attr - Pale_Skin,Young,Blond_Hair

./celeba_pipelines.sh e2e --classify_attributes Smiling --perturb "Pale_Skin,Young,Blond_Hair" --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes High_Cheekbones --perturb "Pale_Skin,Young,Blond_Hair" --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Mouth_Slightly_Open --perturb "Pale_Skin,Young,Blond_Hair" --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Wearing_Lipstick --perturb "Pale_Skin,Young,Blond_Hair" --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Heavy_Makeup --perturb "Pale_Skin,Young,Blond_Hair" --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Wavy_Hair --perturb "Pale_Skin,Young,Blond_Hair" --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
./celeba_pipelines.sh e2e --classify_attributes Arched_Eyebrows --perturb "Pale_Skin,Young,Blond_Hair" --enc_sigma 0.65 --cls_sigmas "0.5" --train_encoder_epochs 20 --cls_loss_weight 0 --adv_loss_weight 0.05 --random_attack_num_samples 10 --recon_loss_weight 0.1 --recon_decoder_type linear --recon_decoder_layers 1024,2048 "$@"
